# -*- coding: utf-8 -*-
"""
Curate quotes.txt -> citaty_monologues.json for DeepSeekThoughts voice bank.
Source file is NOT modified.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "tools" / "citaty_parser" / "output" / "quotes.txt"
OUT = Path(__file__).with_name("citaty_monologues.json")

# Hand-picked adaptations: (id, tiers, tags, gender, soft_dark, ru)
# Adapted to first-person scrap tone — ADAPT further by model, never paste verbatim.
CURATED: list[dict] = [
    # --- calm / uneasy human scraps ---
    {"id": "cit_black_day", "tiers": ["calm", "uneasy"], "tags": ["joke", "money"], "gender": "any",
     "ru": "Откладывать на чёрный день… а другие дни-то бывают?"},
    {"id": "cit_dont_touch", "tiers": ["calm", "uneasy"], "tags": ["joke", "romance"], "gender": "any",
     "ru": "Не прикасайся… обычно это плохо кончается."},
    {"id": "cit_why_die", "tiers": ["uneasy", "scared"], "tags": ["hate", "soft_dark"], "gender": "any", "soft_dark": True,
     "ru": "Почему все просто не могут… взять и сдохнуть?"},
    {"id": "cit_wrong_burial", "tiers": ["uneasy", "calm"], "tags": ["joke", "death"], "gender": "any",
     "ru": "Кажется, похоронили не того. Не парься — придёт и мой день."},
    {"id": "cit_garbage", "tiers": ["uneasy", "combat"], "tags": ["hate", "swagger"], "gender": "any",
     "ru": "Буду краток. Мусор."},
    {"id": "cit_hell_home", "tiers": ["uneasy", "calm"], "tags": ["memory", "regret"], "gender": "any",
     "ru": "Нет хуже ада, чем чужой дом… или свой."},
    {"id": "cit_dont_babble", "tiers": ["calm", "uneasy"], "tags": ["advice"], "gender": "any",
     "ru": "Не болтай — думай. Хорошее жизненное правило."},
    {"id": "cit_street_cat", "tiers": ["calm", "uneasy"], "tags": ["joke", "memory"], "gender": "any",
     "ru": "Нет ничего печальнее уличного кота, который считает себя домашним."},
    {"id": "cit_threat_remove", "tiers": ["scared", "combat"], "tags": ["advice", "hate"], "gender": "any",
     "ru": "Есть угроза — убери её. И не стыдись, если стало легче."},
    {"id": "cit_live_or_habit", "tiers": ["uneasy", "scared", "death"], "tags": ["soft_dark", "wonder"], "gender": "any", "soft_dark": True,
     "ru": "Не знаю — хочу жить… или просто привыкла."},
    {"id": "cit_optimist_fall", "tiers": ["scared", "uneasy"], "tags": ["joke", "fear"], "gender": "any",
     "ru": "Одно хорошо: сорвёмся — так насмерть. Я по жизни оптимист."},
    {"id": "cit_make_a_move", "tiers": ["uneasy", "scared"], "tags": ["advice"], "gender": "any",
     "ru": "Нельзя же думать вечно. Рано или поздно — ход."},
    {"id": "cit_fight_or_die", "tiers": ["scared", "panic", "combat"], "tags": ["fear"], "gender": "any",
     "ru": "Не будешь бороться — умрёшь. Просто."},
    {"id": "cit_grow_up", "tiers": ["calm", "uneasy"], "tags": ["wonder"], "gender": "any",
     "ru": "Взрослеть — значит привыкать к миру. Даже к этому."},
    {"id": "cit_time_slips", "tiers": ["calm", "uneasy"], "tags": ["regret", "memory"], "gender": "any",
     "ru": "Ждём подходящего момента сказать важное… а время уже утекло."},
    {"id": "cit_pain_place", "tiers": ["uneasy", "scared"], "tags": ["body", "regret"], "gender": "any",
     "ru": "Боль не уйдёт. Просто оставь ей место."},
    {"id": "cit_time_ends", "tiers": ["calm", "uneasy"], "tags": ["regret"], "gender": "any",
     "ru": "Всегда думаем, что времени хватит. А потом оно кончается."},
    {"id": "cit_eyes_open", "tiers": ["uneasy", "scared"], "tags": ["fear"], "gender": "any",
     "ru": "Глаза открыты — а всё равно ничего не видел."},
    {"id": "cit_good_still_die", "tiers": ["uneasy", "scared"], "tags": ["fear", "joke"], "gender": "any",
     "ru": "То, что мы хорошие, ещё не значит, что мы не умрём."},
    {"id": "cit_mean_alive", "tiers": ["scared", "combat"], "tags": ["hate", "advice"], "gender": "any",
     "ru": "Лучше злой и живой, чем добрый и мёртвый."},
    {"id": "cit_become_essence", "tiers": ["uneasy", "scared"], "tags": ["wonder"], "gender": "any",
     "ru": "Есть вещи, от которых не сбежать. Они становятся твоей сутью."},
    {"id": "cit_die_for", "tiers": ["calm", "uneasy"], "tags": ["wonder", "memory"], "gender": "any",
     "ru": "Найди то, ради чего стоит умереть… и не желай найти слишком быстро."},
    {"id": "cit_brain_main", "tiers": ["calm", "combat"], "tags": ["joke", "advice"], "gender": "any",
     "ru": "Главное — мозг. Не тупи."},
    {"id": "cit_coward_worse", "tiers": ["uneasy", "scared"], "tags": ["fear"], "gender": "any",
     "ru": "Идиот опасен. Трус — опаснее."},
    {"id": "cit_fix_it", "tiers": ["uneasy", "scared"], "tags": ["advice"], "gender": "any",
     "ru": "Думай не о том, что могло пойти не так — а как это чинить."},
    {"id": "cit_be_kinder", "tiers": ["calm", "uneasy"], "tags": ["advice", "memory"], "gender": "any",
     "ru": "Будьте добрее… будто сегодня последний день. Эх."},
    {"id": "cit_weak_done", "tiers": ["scared", "uneasy"], "tags": ["hate", "fear"], "gender": "any",
     "ru": "Мир не изменился. Слабым — крышка. Как раньше."},
    {"id": "cit_threat_smoke", "tiers": ["uneasy", "scared"], "tags": ["joke", "hate"], "gender": "any",
     "ru": "Забавно: стоит пригрозить смертью — и у всех подгорает."},
    {"id": "cit_saving_hard", "tiers": ["uneasy", "scared"], "tags": ["regret"], "gender": "any",
     "ru": "Спасение людей — тяжёлый труд. Не благодарный."},
    {"id": "cit_fall_optimist", "tiers": ["scared", "uneasy"], "tags": ["joke"], "gender": "any",
     "ru": "Плюс: упадём — разобьёмся насмерть. Оптимист во мне жив."},
    {"id": "cit_someone_takes", "tiers": ["uneasy", "calm"], "tags": ["regret"], "gender": "any",
     "ru": "Есть что-то хорошее — найдётся тот, кто захочет отнять."},
    {"id": "cit_nostalgia_drug", "tiers": ["calm", "uneasy"], "tags": ["memory", "fear"], "gender": "any",
     "ru": "Ностальгия — наркотик. Искажает реальность. Опасно."},
    {"id": "cit_fear_shrinks", "tiers": ["scared", "uneasy"], "tags": ["fear"], "gender": "any",
     "ru": "Чем сильнее боятся — тем глупее. Страх уменьшает мозг."},
    {"id": "cit_care_pain", "tiers": ["calm", "uneasy"], "tags": ["regret", "memory"], "gender": "any",
     "ru": "Заботишься о ком-то — боль идёт в комплекте."},
    {"id": "cit_god_laughs", "tiers": ["calm", "uneasy"], "tags": ["joke", "regret"], "gender": "any",
     "ru": "Бог смеётся, пока мы строим планы."},
    {"id": "cit_forget_people", "tiers": ["scared", "combat"], "tags": ["hate", "memory"], "gender": "any",
     "ru": "Так долго бежишь от мёртвых — забываешь, на что способны живые."},
    {"id": "cit_not_just_survive", "tiers": ["scared", "combat"], "tags": ["hate"], "gender": "any",
     "ru": "Нельзя просто выживать. Надо… пережить."},
    {"id": "cit_life_short", "tiers": ["calm", "uneasy"], "tags": ["wonder"], "gender": "any",
     "ru": "Жизнь только кажется длинной."},
    {"id": "cit_bullet_last", "tiers": ["combat", "scared"], "tags": ["guns", "advice"], "gender": "any",
     "ru": "Пуля — крайняя мера. Крайняя уже близко."},
    {"id": "cit_food_chain", "tiers": ["uneasy", "scared"], "tags": ["fear", "joke"], "gender": "any",
     "ru": "Каждый — еда для кого-то ещё. Приятная мысль."},
    {"id": "cit_nearest_boat", "tiers": ["scared", "uneasy"], "tags": ["advice"], "gender": "any",
     "ru": "Тонешь — плыви к ближайшей шлюпке, не через всё море."},
    {"id": "cit_anger_kills", "tiers": ["scared", "combat"], "tags": ["hate", "advice"], "gender": "any",
     "ru": "Гнев отшибает мозги. А глупость убивает."},
    {"id": "cit_hard_to_trust", "tiers": ["uneasy"], "tags": ["joke"], "gender": "any",
     "ru": "Тяжело верить тому, кто улыбается, получив по морде."},
    {"id": "cit_middle_finger", "tiers": ["uneasy", "scared"], "tags": ["joke", "hate"], "gender": "any",
     "ru": "Вселенная шлёт знак — а ты ей средний палец."},
    {"id": "cit_only_self", "tiers": ["scared", "death"], "tags": ["soft_dark", "regret"], "gender": "any", "soft_dark": True,
     "ru": "Сколько людей убил?… Только себя. По кусочкам."},
    {"id": "cit_nightmares_end", "tiers": ["scared", "uneasy"], "tags": ["fear"], "gender": "any",
     "ru": "Кошмарам приходит конец. Нельзя дать им победить."},
    {"id": "cit_boredom_lucky", "tiers": ["calm", "uneasy"], "tags": ["joke"], "gender": "any",
     "ru": "Душит скука… Значит, повезло. Можно скучать — уже кайф."},
    {"id": "cit_no_fear_back", "tiers": ["uneasy", "scared"], "tags": ["advice"], "gender": "any",
     "ru": "Нельзя возвращаться из-за страха."},
    {"id": "cit_dead_everywhere", "tiers": ["scared", "uneasy"], "tags": ["fear"], "gender": "any",
     "ru": "Мёртвые повсюду. Живые всё меньше похожи на людей."},
    {"id": "cit_their_world", "tiers": ["scared", "uneasy"], "tags": ["fear", "zombie"], "gender": "any",
     "ru": "Это их мир. Мы в нём всего лишь живём."},
    {"id": "cit_not_dying_today", "tiers": ["scared", "panic"], "tags": ["fear", "joke"], "gender": "any",
     "ru": "Сегодня не собираюсь умирать. Проблема — кто-то из нас ошибётся."},
    {"id": "cit_accept_or_eat", "tiers": ["uneasy", "scared"], "tags": ["advice"], "gender": "any",
     "ru": "Случилось. Смирись — иначе съест изнутри."},
    {"id": "cit_finger_off", "tiers": ["combat", "scared"], "tags": ["guns", "advice"], "gender": "any",
     "ru": "Палец на курок — только если готов стрелять."},
    {"id": "cit_tomorrow_may", "tiers": ["uneasy", "scared"], "tags": ["fear"], "gender": "any",
     "ru": "Отложить на завтра? Завтра может и не быть."},
    {"id": "cit_apocalypse_boring", "tiers": ["calm", "uneasy"], "tags": ["joke"], "gender": "any",
     "ru": "Приятно иметь занятие. Никто не знал, каким скучным окажется конец света."},
    {"id": "cit_looting_rule", "tiers": ["uneasy", "calm"], "tags": ["joke", "advice"], "gender": "any",
     "ru": "Первое правило: в этом мире остались только спрятанные вещи."},
    {"id": "cit_cant_survive_doubt", "tiers": ["scared", "death"], "tags": ["fear"], "gender": "any",
     "ru": "Не знаю, смогу ли выжить… Значит — нет."},
    {"id": "cit_play_or_toy", "tiers": ["uneasy", "scared"], "tags": ["hate"], "gender": "any",
     "ru": "Играй — или будешь игрушкой."},
    {"id": "cit_lose_one", "tiers": ["scared", "uneasy"], "tags": ["fear"], "gender": "any",
     "ru": "Не готов потерять одного — потеряешь всех."},
    {"id": "cit_puppies_dead", "tiers": ["scared", "uneasy"], "tags": ["joke", "fear"], "gender": "any",
     "ru": "Думай о хорошем… о щенках. О мёртвых щенках. Отлично."},
    {"id": "cit_no_surrender", "tiers": ["scared", "panic"], "tags": ["hate"], "gender": "any",
     "ru": "Сдаваться живыми нельзя."},
    {"id": "cit_fake_it", "tiers": ["uneasy", "calm"], "tags": ["advice"], "gender": "any",
     "ru": "Притворяйся, пока не станет правдой. Старый трюк."},
    {"id": "cit_safe_alive", "tiers": ["uneasy", "scared"], "tags": ["advice"], "gender": "any",
     "ru": "Быть в безопасности — значит быть живым. Точка."},
    {"id": "cit_kind_wont", "tiers": ["scared", "combat"], "tags": ["hate"], "gender": "any",
     "ru": "Нельзя быть добреньким и рассчитывать выжить."},
    {"id": "cit_lose_by_will", "tiers": ["calm", "uneasy"], "tags": ["regret"], "gender": "any",
     "ru": "Странно терять человека по его же воле."},
    {"id": "cit_heaven_lie", "tiers": ["uneasy", "scared"], "tags": ["soft_dark", "joke"], "gender": "any", "soft_dark": True,
     "ru": "Рай — очередная ложь. Веришь — идиот."},
    {"id": "cit_words_weak", "tiers": ["calm", "uneasy"], "tags": ["regret"], "gender": "any",
     "ru": "Слова бывают беспомощны. Иногда их просто не хватает."},
    {"id": "cit_comfort_weak", "tiers": ["uneasy", "scared"], "tags": ["advice"], "gender": "any",
     "ru": "Расслабимся — комфорт ослабит. Как гниль."},
    {"id": "cit_anger_dumb", "tiers": ["scared", "combat"], "tags": ["hate"], "gender": "any",
     "ru": "Злость делает тупым. Из-за тупости и гибнут."},
    {"id": "cit_nice_got_nowhere", "tiers": ["uneasy", "calm"], "tags": ["joke", "memory"], "gender": "any",
     "ru": "Милый характер ни к чему не привёл. А вот ум — да."},
    {"id": "cit_dead_haunt", "tiers": ["scared", "uneasy"], "tags": ["fear", "zombie"], "gender": "any",
     "ru": "Выживших всегда будут преследовать мёртвые."},
    {"id": "cit_better_books", "tiers": ["calm", "uneasy"], "tags": ["joke", "memory"], "gender": "any",
     "ru": "Знал бы, что миру конец — взял бы книги получше."},
    {"id": "cit_was_nobody", "tiers": ["calm", "uneasy"], "tags": ["memory", "regret"], "gender": "any",
     "ru": "Кем был до всего этого? Никем. Пустым местом."},
    {"id": "cit_hurt_survive", "tiers": ["scared", "uneasy"], "tags": ["fear"], "gender": "any",
     "ru": "Пострадавшие опасны — они знают, как выживать."},
    {"id": "cit_habits_useless", "tiers": ["calm", "uneasy"], "tags": ["wonder"], "gender": "any",
     "ru": "Мозг хранит привычки даже когда они уже бесполезны."},
    {"id": "cit_crack_light", "tiers": ["calm", "uneasy"], "tags": ["wonder"], "gender": "any",
     "ru": "Иногда можно дать трещину — чтобы впустить свет."},
    {"id": "cit_soul_pieces", "tiers": ["uneasy", "scared", "death"], "tags": ["soft_dark", "regret"], "gender": "any", "soft_dark": True,
     "ru": "Сколько кусков души можно потерять, прежде чем перестанешь чувствовать себя человеком?"},
    {"id": "cit_people_die", "tiers": ["uneasy", "scared"], "tags": ["fear"], "gender": "any",
     "ru": "Люди и раньше умирали. Это нельзя остановить."},
    {"id": "cit_wait_death", "tiers": ["scared", "death"], "tags": ["soft_dark", "fear"], "gender": "any", "soft_dark": True,
     "ru": "Есть кое-что страшнее смерти — день за днём её ждать."},
    {"id": "cit_hell_full", "tiers": ["scared", "uneasy"], "tags": ["zombie", "fear"], "gender": "any",
     "ru": "Когда в аду не останется места — мёртвые будут среди нас. Уже."},
    {"id": "cit_too_good", "tiers": ["uneasy", "calm"], "tags": ["fear", "advice"], "gender": "any",
     "ru": "Выглядит слишком хорошо, чтобы быть правдой… значит, так и есть."},
    {"id": "cit_wrong_river", "tiers": ["calm", "uneasy"], "tags": ["memory", "joke"], "gender": "any",
     "ru": "Сидишь на берегу ждать труп врага… а река — не та."},
    {"id": "cit_fire_family", "tiers": ["calm", "uneasy"], "tags": ["joke", "memory"], "gender": "any",
     "ru": "Все рыжие… не семья, а пожар."},
    {"id": "cit_wine_choice", "tiers": ["calm"], "tags": ["joke", "food"], "gender": "any",
     "ru": "В винах не разбираюсь. Главное вовремя сказать: прекрасный выбор."},
    {"id": "cit_alstro", "tiers": ["calm", "uneasy"], "tags": ["joke", "memory"], "gender": "any",
     "ru": "Аллергия на цветы — вот и весь мой ботанический талант."},
    {"id": "cit_stagnation", "tiers": ["calm", "uneasy"], "tags": ["joke"], "gender": "any",
     "ru": "В отношениях стагнация. Второй «пошёл вон» за полдня."},
    {"id": "cit_sharks", "tiers": ["scared", "uneasy"], "tags": ["joke", "fear"], "gender": "any",
     "ru": "Поздно драпать, когда акулы уже ноги доедают."},
    {"id": "cit_nerves_pork", "tiers": ["uneasy", "calm"], "tags": ["joke", "food"], "gender": "any",
     "ru": "Нервные клетки, как сгоревшая свинина, не восстанавливаются."},
    {"id": "cit_food_life", "tiers": ["calm"], "tags": ["food", "desire"], "gender": "any",
     "ru": "Еда — страсть. Еда — любовь. Еда — жизнь. Даже сейчас."},
    {"id": "cit_old_for_this", "tiers": ["uneasy", "scared"], "tags": ["joke", "body"], "gender": "any",
     "ru": "Я слишком стар для всего этого дерьма."},
    {"id": "cit_storm_better", "tiers": ["uneasy", "scared"], "tags": ["joke", "advice"], "gender": "any",
     "ru": "Лучше обделаться в шторм, чем от прогноза погоды."},
    {"id": "cit_telepathy_gun", "tiers": ["combat", "scared"], "tags": ["guns", "joke"], "gender": "any",
     "ru": "Лучший способ передать мысль на расстояние — прицельный выстрел."},
    {"id": "cit_drink_measure", "tiers": ["calm", "uneasy"], "tags": ["joke"], "gender": "any",
     "ru": "Когда квасишь — соблюдай меру. Иначе выпьешь меньше."},
    {"id": "cit_lady_luck", "tiers": ["uneasy", "scared"], "tags": ["joke", "regret"], "gender": "any",
     "ru": "Леди Удача — обыкновенная… а наличные кончились."},
    {"id": "cit_broken_mirror", "tiers": ["calm", "uneasy"], "tags": ["memory", "regret"], "gender": "any",
     "ru": "Прошлое — разбитое зеркало. Собираешь осколки — режешься."},
    {"id": "cit_kind_eyes", "tiers": ["uneasy", "scared"], "tags": ["joke"], "gender": "any",
     "ru": "Глаза добрые. Рубашка — смирительная."},
    {"id": "cit_run_chase", "tiers": ["scared", "panic"], "tags": ["fear", "body"], "gender": "any",
     "ru": "Чем быстрее бежишь, тем больше кажется, что тебя в самом деле преследуют."},
    {"id": "cit_no_happy_end", "tiers": ["scared", "death"], "tags": ["soft_dark"], "gender": "any", "soft_dark": True,
     "ru": "Спастись — не для меня. Хэппи-энда не будет."},
    {"id": "cit_evidence_late", "tiers": ["combat", "scared"], "tags": ["guns", "joke"], "gender": "any",
     "ru": "Собирать улики поздно уже пару сотен патронов назад."},
    {"id": "cit_wife_dream", "tiers": ["calm", "uneasy", "death"], "tags": ["memory", "soft_dark"], "gender": "male", "soft_dark": True,
     "ru": "Мне снилась жена. Она была мертва… и всё было в порядке."},
    {"id": "cit_bloody_valentines", "tiers": ["scared", "death"], "tags": ["soft_dark", "joke"], "gender": "any", "soft_dark": True,
     "ru": "А смерть писала мне кровавые валентинки."},
    {"id": "cit_worse_coming", "tiers": ["scared", "uneasy"], "tags": ["fear"], "gender": "any",
     "ru": "Кажется, всё самое ужасное уже было… и тут надвигается ещё хуже."},
    {"id": "cit_gun_courtesy", "tiers": ["scared", "combat"], "tags": ["guns", "swagger"], "gender": "any",
     "ru": "Дуло смотрело в лицо. Ответил любезностью на любезность."},
    {"id": "cit_devil_snow", "tiers": ["calm", "uneasy"], "tags": ["weather", "joke"], "gender": "any",
     "ru": "Снег падал, как конфетти на празднике дьявола."},
    {"id": "cit_bye_dream", "tiers": ["calm", "uneasy"], "tags": ["regret", "memory"], "gender": "any",
     "ru": "Скоро рассвет. Прощай, американская мечта… или любая."},
    {"id": "cit_end_personal", "tiers": ["uneasy", "scared"], "tags": ["wonder"], "gender": "any",
     "ru": "Конец света у каждого свой. Если придёт — не покажется банальным."},
    {"id": "cit_dead_talk", "tiers": ["scared", "uneasy"], "tags": ["fear", "zombie"], "gender": "any",
     "ru": "Покойники знают ответы. И начав говорить — уже не замолчат."},
    {"id": "cit_love_illusion", "tiers": ["calm", "uneasy"], "tags": ["romance", "regret"], "gender": "any",
     "ru": "Любовь — когда тебе вручают иллюзию выбора."},
    {"id": "cit_push_first", "tiers": ["uneasy", "scared"], "tags": ["hate", "joke"], "gender": "any",
     "ru": "Даже на краю пропасти думают, кого спихнуть первым… а не как спастись."},
    {"id": "cit_hide_pro", "tiers": ["calm", "uneasy"], "tags": ["joke", "memory"], "gender": "any",
     "ru": "В детстве в прятки играл профессионально. Меня до сих пор некоторые ищут."},
    {"id": "cit_mirror_blame", "tiers": ["uneasy", "scared"], "tags": ["regret"], "gender": "any",
     "ru": "Кто виноват? Добро пожаловать к зеркалу."},
    {"id": "cit_simple_joy", "tiers": ["calm"], "tags": ["wonder", "memory"], "gender": "any",
     "ru": "Радуемся простому… не всегда понимая, что простое — и есть ценное."},
    {"id": "cit_veg_meat", "tiers": ["calm"], "tags": ["joke", "food"], "gender": "any",
     "ru": "Любое вегетарианское блюдо вкуснее с мясом. Факт."},
    {"id": "cit_best_not_good", "tiers": ["uneasy", "calm"], "tags": ["joke"], "gender": "any",
     "ru": "Лучший — не значит хороший. Значит, остальные хуже."},
    {"id": "cit_alone_wait_death", "tiers": ["death", "scared"], "tags": ["soft_dark"], "gender": "any", "soft_dark": True,
     "ru": "Страшнее смерти — сидеть и ждать её каждый день."},
    {"id": "cit_humanity_choice", "tiers": ["calm", "uneasy"], "tags": ["wonder"], "gender": "any",
     "ru": "Мир, каким знали — исчез. Но человечность — всё ещё выбор."},
    {"id": "cit_realist_road", "tiers": ["calm", "uneasy"], "tags": ["advice"], "gender": "any",
     "ru": "Пессимист бьётся головой, оптимист спотыкается. Реалист выбирает дорогу сам."},
]


def main() -> None:
    assert SRC.exists(), f"missing source {SRC}"
    entries = []
    for e in CURATED:
        item = {
            "id": e["id"],
            "tiers": e["tiers"],
            "tags": e["tags"],
            "gender": e.get("gender", "any"),
            "soft_dark": bool(e.get("soft_dark", False)),
            "ru": e["ru"],
            "source": "citaty_parser",
        }
        entries.append(item)
    OUT.write_text(
        json.dumps({"version": 1, "monologues": entries}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {len(entries)} -> {OUT}")
    assert len(entries) >= 80


if __name__ == "__main__":
    main()
